### ISSUE TITLE
AttributeError: 'float' object has no attribute 'unsqueeze'

### ISSUE THREAD

**Issue by clemense** [WangFeng18/3d-gaussian-splatting#13]
Hi,
After some training time I'm getting
```
loss: 0.386204/0.673039/6.7382/[882569/237845]:lr: 0.0228|0.0228|0.0023|0.0023|0.0023 grad: [0.000000|0.000000|0.000000|0.000000|0.000000]:  10%|██▍                      | 700/7001 [00:31<04:47, 21.90it/s]
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    trainer.train()
  File "train.py", line 206, in train
    output = self.train_step(i_iter, bar)
  File "train.py", line 162, in train_step
    self.accum_max_grad/(self.grad_counter+1e-3).unsqueeze(dim=-1), 
AttributeError: 'float' object has no attribute 'unsqueeze'
```
Any idea what the problem could be?

Thanks!

**Comment by clemense** [comment]
Nevermind, wrapping `self.grad_counter+1e-3` in a tensor fixed it.
